version: "3.8"

services:
  app:
    container_name: flask-metrics-app
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: always
